version: '3'
volumes:
    mysql_data:
services:
    project-nginx-service:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        container_name: project-nginx-container
        volumes:
            - ./../:/var/www/project/
        ports: ['7551:80']
        networks:
            - project-network
#            - sf64-1-app-network
    project-php-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: project-php-container
        ports: ['7552:9000']
        volumes:
            - ./../:/var/www/project/
            - ./../vendor:/var/www/project/vendor
        networks:
            - project-network
#            - sf64-1-app-network
        depends_on:
            project-mysql-service:
                condition: service_healthy
            project-redis-service:
                condition: service_healthy
            project-rabbitmq-service:
                condition: service_healthy
    project-mysql-service:
        image: mysql
        container_name: project-mysql-container
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--authentication_policy=caching_sha2_password']
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports: ['7553:3306']
        volumes:
            - ./mysql:/var/lib/mysql
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
            interval: 4s
            timeout: 20s
            retries: 15
        networks:
            - project-network
    project-phpmyadmin-service:
        image: phpmyadmin/phpmyadmin:latest
        container_name: project-phpmyadmin-container
        environment:
            PMA_HOST: project-mysql-service
            PMA_USER: root
            PMA_PASSWORD: root
        ports: ['7554:80']
        depends_on:
            - project-mysql-service
        volumes:
            - ./phpmyadmin/:/var/www/project/docker/phpmyadmin/
        networks:
            - project-network
    project-redis-service:
        image: library/redis:alpine
        container_name: project-redis-container
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 5s
            timeout: 30s
            retries: 15
        tty: true
        networks:
            - project-network
    project-rabbitmq-service:
        build:
            context: .
            dockerfile: ./docker-conf/rabbitmq/www/Dockerfile
        container_name: project-rabbitmq-container
        ports: [ '7555:5672', '17555:15672' ]
        volumes:
            - ./docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia
            - ./docker-conf/rabbitmq/log/:/var/log/rabbitmq
        healthcheck:
            test: rabbitmq-diagnostics check_port_connectivity
            interval: 4s
            timeout: 20s
            retries: 15
        networks:
            - project-network
#            - sf64-1-app-network
networks:
    project-network:
        driver: bridge
#    sf64-1-app-network:
#        driver: bridge
#        external: true
